/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const PromptWithViews = IDL.Record({
  'id' : IDL.Nat,
  'complexity' : IDL.Int,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'view_count' : IDL.Nat,
  'created_at' : Timestamp,
});
export const PromptError = IDL.Variant({
  'InvalidComplexity' : IDL.Text,
  'NotFound' : IDL.Null,
  'InvalidTitle' : IDL.Text,
  'InvalidContent' : IDL.Text,
});
export const Result = IDL.Variant({
  'ok' : PromptWithViews,
  'err' : PromptError,
});

export const idlService = IDL.Service({
  'createPrompt' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [Result], []),
  'getPrompt' : IDL.Func([IDL.Nat], [Result], []),
  'getPrompts' : IDL.Func([], [IDL.Vec(PromptWithViews)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const PromptWithViews = IDL.Record({
    'id' : IDL.Nat,
    'complexity' : IDL.Int,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'view_count' : IDL.Nat,
    'created_at' : Timestamp,
  });
  const PromptError = IDL.Variant({
    'InvalidComplexity' : IDL.Text,
    'NotFound' : IDL.Null,
    'InvalidTitle' : IDL.Text,
    'InvalidContent' : IDL.Text,
  });
  const Result = IDL.Variant({ 'ok' : PromptWithViews, 'err' : PromptError });
  
  return IDL.Service({
    'createPrompt' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [Result], []),
    'getPrompt' : IDL.Func([IDL.Nat], [Result], []),
    'getPrompts' : IDL.Func([], [IDL.Vec(PromptWithViews)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };