/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PromptError = { 'InvalidComplexity' : string } |
  { 'NotFound' : null } |
  { 'InvalidTitle' : string } |
  { 'InvalidContent' : string };
export interface PromptWithViews {
  'id' : bigint,
  'complexity' : bigint,
  'title' : string,
  'content' : string,
  'view_count' : bigint,
  'created_at' : Timestamp,
}
export type Result = { 'ok' : PromptWithViews } |
  { 'err' : PromptError };
export type Timestamp = bigint;
export interface _SERVICE {
  'createPrompt' : ActorMethod<[string, string, bigint], Result>,
  'getPrompt' : ActorMethod<[bigint], Result>,
  'getPrompts' : ActorMethod<[], Array<PromptWithViews>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];