/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PromptWithViews {
    id: bigint;
    complexity: bigint;
    title: string;
    content: string;
    view_count: bigint;
    created_at: Timestamp;
}
export type Timestamp = bigint;
export type Result = {
    __kind__: "ok";
    ok: PromptWithViews;
} | {
    __kind__: "err";
    err: PromptError;
};
export type PromptError = {
    __kind__: "InvalidComplexity";
    InvalidComplexity: string;
} | {
    __kind__: "NotFound";
    NotFound: null;
} | {
    __kind__: "InvalidTitle";
    InvalidTitle: string;
} | {
    __kind__: "InvalidContent";
    InvalidContent: string;
};
export interface backendInterface {
    createPrompt(title: string, content: string, complexity: bigint): Promise<Result>;
    getPrompt(id: bigint): Promise<Result>;
    getPrompts(): Promise<Array<PromptWithViews>>;
}
import type { PromptError as _PromptError, PromptWithViews as _PromptWithViews, Result as _Result } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createPrompt(arg0: string, arg1: string, arg2: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createPrompt(arg0, arg1, arg2);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPrompt(arg0, arg1, arg2);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrompt(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrompt(arg0);
                return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrompt(arg0);
            return from_candid_Result_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPrompts(): Promise<Array<PromptWithViews>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPrompts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPrompts();
            return result;
        }
    }
}
function from_candid_PromptError_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PromptError): PromptError {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PromptWithViews;
} | {
    err: _PromptError;
}): {
    __kind__: "ok";
    ok: PromptWithViews;
} | {
    __kind__: "err";
    err: PromptError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_PromptError_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    InvalidComplexity: string;
} | {
    NotFound: null;
} | {
    InvalidTitle: string;
} | {
    InvalidContent: string;
}): {
    __kind__: "InvalidComplexity";
    InvalidComplexity: string;
} | {
    __kind__: "NotFound";
    NotFound: null;
} | {
    __kind__: "InvalidTitle";
    InvalidTitle: string;
} | {
    __kind__: "InvalidContent";
    InvalidContent: string;
} {
    return "InvalidComplexity" in value ? {
        __kind__: "InvalidComplexity",
        InvalidComplexity: value.InvalidComplexity
    } : "NotFound" in value ? {
        __kind__: "NotFound",
        NotFound: value.NotFound
    } : "InvalidTitle" in value ? {
        __kind__: "InvalidTitle",
        InvalidTitle: value.InvalidTitle
    } : "InvalidContent" in value ? {
        __kind__: "InvalidContent",
        InvalidContent: value.InvalidContent
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
